### ISSUE TITLE
A beansdb Crash Issue

### ISSUE THREAD

**Issue by xuyin224** [douban/beansdb#23]
Hi, 

We recently encounter a beansdb crash issue, and the gdb trace is like this:
#0  decode_record (buf=0x7fd0a3953b90 <Address 0x7fd0a3953b90 out of bounds>,
    size=4124399360, decomp=true) at src/record.c:147
#1  0x000000000040bee4 in bc_get (bc=0x28204c0,
    key=0x7fd0d9a107e4 "-3418702703845858593") at src/bitcask.c:436
#2  0x000000000040e638 in hs_get (store=0x235b610,
    key=0x7fd0d9a107e4 "-3418702703845858593", vlen=0x7fd365c4231c,
    flag=0x7fd365c42318) at src/hstore.c:322

After trace into the code, we found that the reason is that, in the following code:
DataRecord* bc_get(Bitcask *bc, const char* key)
{
    Item *item = ht_get(bc->tree, key);
    if (NULL == item) return NULL;
    if (item->ver < 0){
        free(item);
        return NULL;
    }

    uint32_t bucket = item->pos & 0xff;
    uint32_t pos = item->pos & 0xffffff00;
    if (bucket > bc->curr) {
        fprintf(stderr, "BUG: invalid bucket %d > %d\n", bucket, bc->curr);
        ht_remove(bc->tree, key);
        free(item);
        return NULL;
    }
    DataRecord* r = NULL;
    if (bucket == bc->curr) {
        pthread_mutex_lock(&bc->buffer_lock);
        if (bucket == bc->curr && pos >= bc->wbuf_start_pos){
            uint32_t p = pos - bc->wbuf_start_pos;
            r = decode_record(bc->write_buffer + p, bc->wbuf_curr_pos - p, true);
        }
        pthread_mutex_unlock(&bc->buffer_lock);

   .....
}

The code get the item and pos first. However, the item->pos seems possibly to be changed by other threads(possibly delete or flush, because the crash happens more on those machine that is deleting data and use flush all to get back the space ), which caused  bc->write_buffer + p to be an invalid value. beansdb crashed when  bc->write_buffer + p ovelflow, or get an invalid value when it is not overflow.

We intend to change, but it relates too many lock operation, we are not 100% sure of safe changing. We are appreciate if you can help to solve this bug

**Comment by youngsofun** [comment]
hi, douban had found and solved  this bug (and some others) in our internal version，we will try to push it to github next week。Sorry for too late to do that。

**Comment by xuyin224** [comment]
Great! Thanks for your help.

**Comment by xuyin224** [comment]
Hi,
May I know when this update will be pushed?

**Comment by youngsofun** [comment]
done.
plz refer to https://github.com/douban/beansdb/blob/master/ChangeLog#L7.
beansdb now use zlog, you need a conf file like https://github.com/douban/beansdb/blob/master/beansdb_log.conf,  remember to disable access log.

**Comment by xuyin224** [comment]
Great! Thanks a lot for the commit, will try and see
