### ISSUE TITLE
Another Segmentation fault of the new version

### ISSUE THREAD

**Issue by xuyin224** [douban/beansdb#25]
Hi,
Sorry to trouble again, but we meet another Segmentation fault, which causes beansdb restarted.
This issue seems related to issue 23, or may be the bug of issue 23 is not solved in the new version?
the gdb info:
#0  get_item_hash (tree=<value optimized out>, node=<value optimized out>, it=0x7f975472b020, keyhash=<value optimized out>) at htree.c:422
#1  0x0000000000409e85 in ht_get_withbuf (tree=0x7f9745b97570, key=<value optimized out>, len=<value optimized out>, buf=0x7f975472b020 "\005p\220\036\001", lock=true) at htree.c:1090
#2  0x0000000000409f32 in ht_get_maybe_tmp (tree=0x7f9745b97570, key=0x7f964d90ea84 "8451159738723177110", is_tmp=0x7f975472b42c, buf=0x7f975472b020 "\005p\220\036\001") at htree.c:1107
#3  0x000000000041371c in bc_get (bc=0x188b080, key=0x7f964d90ea84 "8451159738723177110", ret_pos=0x7f975472b4cc, return_deleted=true) at bitcask.c:981
#4  0x00000000004179f0 in hs_get (store=0x1229470, key=0x7f964d90ea84 "8451159738723177110", vlen=0x7f975472b51c, flag=0x7f975472b518) at hstore.c:397
#5  0x00000000004084ea in item_get (key=0x7f964d90ea84 "8451159738723177110", nkey=19) at item.c:221
#6  0x0000000000405fc3 in process_get_command (c=0x7f964c9e9af0, command=<value optimized out>) at beansdb.c:918
#7  process_command (c=0x7f964c9e9af0, command=<value optimized out>) at beansdb.c:1214
#8  0x00000000004073e4 in try_read_command (c=0x7f964c9e9af0) at beansdb.c:1362
#9  drive_machine (c=0x7f964c9e9af0) at beansdb.c:1590
#10 0x0000000000408b42 in worker_main (arg=<value optimized out>) at thread.c:218
#11 0x00000032248079d1 in start_thread () from /lib64/libpthread.so.0
#12 0x00000032244e88fd in clone () from /lib64/libc.so.6

The possible reason of crash is p_len is not accessable,
(gdb)  p p_len
Cannot access memory at address 0x7f974800000a

I did not see any ERROR log in the beansdb-error.log

**Comment by youngsofun** [comment]
that is why I recommend you to try to rebuild htree, even if our changes is compatible, there may be old bugs which is persisted in the htree file.
we have NOT met crash like this or in #23 for a long time, so we are not sure whether these two issue should be regarded as critical  bug and really dive into it right now.

**Comment by xuyin224** [comment]
Ok, I see. I will try to rebuild and see.
