### ISSUE TITLE
create a tag for v0.7.1.4

### ISSUE THREAD

**Issue by mozillazg** [douban/beansdb#28]

**Comment by zzl0** [comment]
@mozillazg yeah, I created a new tag, thanks for your interest. And we are developing a new version of beansdb (now we call it gobeansdb), the main advantages are:
1. Reduced the memory size of htree (e.g. 18G -> 8G).
2. Better support for large number of buckets.
3. It uses Golang, it's more robust and easy to maintain, at least we hope so :)

If you know Chinese, you can get more details here https://www.douban.com/note/169100405/#43375815

If you are interested in gobeansdb, please let me know.

PS, gobeansdb is running in production now.

**Comment by mozillazg** [comment]
@zzl0 Thanks. It looks like a very interesting project, I'll read it later.
